apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapp
spec:
  selector:
    app: fastapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
      nodePort: 31110