# Użyj obrazu Python jako podstawy
FROM python:3.10-slim

# Ustaw katalog roboczy
WORKDIR /app

# Skopiuj plik requirements.txt i zainstaluj zależności
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Skopiuj resztę aplikacji
COPY . .

# Uruchom serwer FastAPI
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]